version: "3"
services:
  app:
    image: "php.7.4.1-apache"
    environment:
      APACHE_DOCUMENT_ROOT: /src/app/public
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    links:
      - postgres
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mishatestpass
      POSTGRES_DB: docker
    ports:
      - "5432:5432"
  adminer:
    image: "adminer:latest"
    restart: always
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: docker
    ports:
      - "8081:8080"
