version: "3"
services:
  app:
    image: "php.7.4.1-apache"
    environment:
      APACHE_DOCUMENT_ROOT: /src/app/public
    build: .
    depends_on:
      - mysql
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    links:
      - mysql
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=mishatestpass
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    links:
      - mysql
    ports:
      - "8003:80"
    environment:
      MYSQL_ROOT_PASSWORD: mishatestpass
      PMA_HOST: mysql